// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file CompleteTypeObject.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_COMPLETE_TYPE_OBJECT_H_
#define _FAST_DDS_GENERATED_COMPLETE_TYPE_OBJECT_H_


#include <fastrtps/types/TypeObject.h>
#include <map>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(Complete_SOURCE)
#define Complete_DllAPI __declspec( dllexport )
#else
#define Complete_DllAPI __declspec( dllimport )
#endif // Complete_SOURCE
#else
#define Complete_DllAPI
#endif
#else
#define Complete_DllAPI
#endif // _WIN32

using namespace eprosima::fastrtps::types;

eProsima_user_DllExport void registerCompleteTypes();

eProsima_user_DllExport const TypeIdentifier* GetTimestampIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetTimestampObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalTimestampObject();
eProsima_user_DllExport const TypeObject* GetCompleteTimestampObject();

eProsima_user_DllExport const TypeIdentifier* GetPointIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetPointObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalPointObject();
eProsima_user_DllExport const TypeObject* GetCompletePointObject();

eProsima_user_DllExport const TypeIdentifier* GetMessageDescriptorIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMessageDescriptorObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalMessageDescriptorObject();
eProsima_user_DllExport const TypeObject* GetCompleteMessageDescriptorObject();

eProsima_user_DllExport const TypeIdentifier* GetMessageIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMessageObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalMessageObject();
eProsima_user_DllExport const TypeObject* GetCompleteMessageObject();

eProsima_user_DllExport const TypeIdentifier* GetCompleteDataIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetCompleteDataObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalCompleteDataObject();
eProsima_user_DllExport const TypeObject* GetCompleteCompleteDataObject();


#endif // _FAST_DDS_GENERATED_COMPLETE_TYPE_OBJECT_H_