name: install_mcap_dependencies
description: Install and setup lz4 and zstd

inputs:

  cmake_build_type:
    description: Specify the build type on single-configuration generators
    required: true
    default: Release

runs:
  using: composite
  steps:

    # LINUX
    - name: Install in ubuntu
      uses: eProsima/eProsima-CI/ubuntu/install_apt_packages@v0
      if: runner.os == 'Linux'
      with:
        packages: liblz4-dev libzstd-dev

    # WINDOWS
    - name: Download vcpkg
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        git clone https://github.com/Microsoft/vcpkg.git ${{ github.workspace }}\vcpkg

    - name: Install vcpkg
      if: runner.os == 'Windows'
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgGitCommitId: '64fabc9401d9296273ed67cd8c39f92c113f9ea5'

    - name: Install lz4 and zstd
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        vcpkg install lz4 zstd --triplet x64-windows --vcpkg-root ${{ env.VCPKG_ROOT }}
        "vcpkg_install_path=${{ github.workspace }}\vcpkg\installed\x64-windows" | Out-File -FilePath $env:GITHUB_ENV -Append
        if ("${{ inputs.cmake_build_type }}" -eq "Release") {
          "${{ github.workspace }}\vcpkg\installed\x64-windows\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        } else {
          "${{ github.workspace }}\vcpkg\installed\x64-windows\debug\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        }
