dds:
  domain: 0

  allowlist:
    - name: "topic_name"
    - name: "HelloWorldTopic"
      type: "HelloWorld"

  blocklist:
    - name: "topic_to_block"
      type: "type_to_block"

  builtin-topics:
    - name: "HelloWorldTopic"
      type: "HelloWorld"

  topics:
    - name: "temperature/*"
      type: "temperature/types/*"
      qos:
        max-rx-rate: 15
        downsampling: 2

  ignore-participant-flags: filter_same_process
  transport: shm
  whitelist-interfaces:
    - "127.0.0.1"

recorder:
  output:
    filename: "output"
    path: "."
    timestamp-format: "%Y-%m-%d_%H-%M-%S_%Z"
    local-timestamp: false

  buffer-size: 50
  event-window: 60
  log-publish-time: false
  only-with-type: false
  compression:
    algorithm: lz4
    level: slowest
    force: true
  record-types: true

remote-controller:
  enable: true
  domain: 10
  initial-state: "PAUSED"
  command-topic-name: "/ddsrecorder/command"
  status-topic-name: "/ddsrecorder/status"

specs:
  threads: 8
  max-pending-samples: 10
  cleanup-period: 90

  qos:
    max-rx-rate: 20
    downsampling: 3
