name: Install DDS Recorder subpackages
description: Install and setup DDS Recorder subpackages for linking and building application in Windows
inputs:
  cmake_extra_args:
    description: 'Specifies cmake arguments different from default'
    required: false
    default: ' '
  cmake_build_type:
    description: 'Specifies the build type on single-configuration generators'
    required: true
    default: 'Release'
  subpackage:
    description: 'Specifies the name of the subpackage to install'
    required: true
  subpackage_dir:
    description: 'Specifies the path of the subpackage to install'
    required: true
  cmake_prefix_path:
    description: 'Sets CMAKE_PREFIX_PATH used for searching by FIND_XXX().'
    required: false
    default: ''
runs:
  using: composite
  steps:
  - run: >
      cmake -DCMAKE_PREFIX_PATH="${{ inputs.cmake_prefix_path }}" `
        -DCMAKE_CXX_FLAGS="/WX /EHsc" -DBUILD_TOOL_TESTS=ON -DBUILD_LIBRARY_TESTS=ON `
        ${{ inputs.cmake_extra_args }} `
        -B build\${{ inputs.subpackage }} -A x64 -T host=x64 DDS-Recorder/${{ inputs.subpackage_dir }};
      cmake --build build\${{ inputs.subpackage }} --config ${{ inputs.cmake_build_type }} --target install;

    shell: pwsh
