name: 'install-apt-packages'
description: 'Install necessary apt packages'
runs:
  using: "composite"
  steps:
    - id: install-apt-packages
      run: |
        sudo apt update && sudo apt -y install \
          clang-tidy \
          curl \
          doxygen \
          graphviz \
          grep \
          imagemagick \
          libasio-dev \
          libtinyxml2-dev \
          libyaml-cpp-dev \
          lcov \
          python3 \
          python3-pip \
          python3-sphinxcontrib.spelling \
          python3-venv \
          software-properties-common \
          wget \
          swig \
          libpython3-dev \
          liblz4-dev \
          libzstd-dev \
          lz4 \
          systemd-coredump
        ulimit -c unlimited
      shell: bash
