// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file basic_struct.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_BASIC_STRUCT_H_
#define _FAST_DDS_GENERATED_BASIC_STRUCT_H_


#include <fastrtps/utils/fixed_size_string.hpp>

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(basic_struct_SOURCE)
#define basic_struct_DllAPI __declspec( dllexport )
#else
#define basic_struct_DllAPI __declspec( dllimport )
#endif // basic_struct_SOURCE
#else
#define basic_struct_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define basic_struct_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


/*!
 * @brief This class represents the structure TheOtherObject defined by the user in the IDL file.
 * @ingroup BASIC_STRUCT
 */
class TheOtherObject
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport TheOtherObject();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~TheOtherObject();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object TheOtherObject that will be copied.
     */
    eProsima_user_DllExport TheOtherObject(
            const TheOtherObject& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object TheOtherObject that will be copied.
     */
    eProsima_user_DllExport TheOtherObject(
            TheOtherObject&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object TheOtherObject that will be copied.
     */
    eProsima_user_DllExport TheOtherObject& operator =(
            const TheOtherObject& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object TheOtherObject that will be copied.
     */
    eProsima_user_DllExport TheOtherObject& operator =(
            TheOtherObject&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x TheOtherObject object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const TheOtherObject& x) const;

    /*!
     * @brief Comparison operator.
     * @param x TheOtherObject object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const TheOtherObject& x) const;

    /*!
     * @brief This function sets a value in member some_num
     * @param _some_num New value for member some_num
     */
    eProsima_user_DllExport void some_num(
            int32_t _some_num);

    /*!
     * @brief This function returns the value of member some_num
     * @return Value of member some_num
     */
    eProsima_user_DllExport int32_t some_num() const;

    /*!
     * @brief This function returns a reference to member some_num
     * @return Reference to member some_num
     */
    eProsima_user_DllExport int32_t& some_num();


    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const TheOtherObject& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    int32_t m_some_num;
};
/*!
 * @brief This class represents the structure basic_struct defined by the user in the IDL file.
 * @ingroup BASIC_STRUCT
 */
class basic_struct
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport basic_struct();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~basic_struct();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object basic_struct that will be copied.
     */
    eProsima_user_DllExport basic_struct(
            const basic_struct& x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object basic_struct that will be copied.
     */
    eProsima_user_DllExport basic_struct(
            basic_struct&& x) noexcept;

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object basic_struct that will be copied.
     */
    eProsima_user_DllExport basic_struct& operator =(
            const basic_struct& x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object basic_struct that will be copied.
     */
    eProsima_user_DllExport basic_struct& operator =(
            basic_struct&& x) noexcept;

    /*!
     * @brief Comparison operator.
     * @param x basic_struct object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const basic_struct& x) const;

    /*!
     * @brief Comparison operator.
     * @param x basic_struct object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const basic_struct& x) const;

    /*!
     * @brief This function copies the value in member sub_struct
     * @param _sub_struct New value to be copied in member sub_struct
     */
    eProsima_user_DllExport void sub_struct(
            const TheOtherObject& _sub_struct);

    /*!
     * @brief This function moves the value in member sub_struct
     * @param _sub_struct New value to be moved in member sub_struct
     */
    eProsima_user_DllExport void sub_struct(
            TheOtherObject&& _sub_struct);

    /*!
     * @brief This function returns a constant reference to member sub_struct
     * @return Constant reference to member sub_struct
     */
    eProsima_user_DllExport const TheOtherObject& sub_struct() const;

    /*!
     * @brief This function returns a reference to member sub_struct
     * @return Reference to member sub_struct
     */
    eProsima_user_DllExport TheOtherObject& sub_struct();

    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(
            const basic_struct& data,
            size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(
            eprosima::fastcdr::Cdr& cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(
            eprosima::fastcdr::Cdr& cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
            size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(
            eprosima::fastcdr::Cdr& cdr) const;

private:

    TheOtherObject m_sub_struct;
};

#endif // _FAST_DDS_GENERATED_BASIC_STRUCT_H_