// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file basic_structTypeObject.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "basic_struct.h"
#include "basic_structTypeObject.h"
#include <utility>
#include <sstream>
#include <fastrtps/rtps/common/SerializedPayload.h>
#include <fastrtps/utils/md5.h>
#include <fastrtps/types/TypeObjectFactory.h>
#include <fastrtps/types/TypeNamesGenerator.h>
#include <fastrtps/types/AnnotationParameterValue.h>
#include <fastcdr/FastBuffer.h>
#include <fastcdr/Cdr.h>

using namespace eprosima::fastrtps::rtps;

void registerbasic_structTypes()
{
    TypeObjectFactory *factory = TypeObjectFactory::get_instance();
    factory->add_type_object("TheOtherObject", GetTheOtherObjectIdentifier(true),
    GetTheOtherObjectObject(true));
    factory->add_type_object("TheOtherObject", GetTheOtherObjectIdentifier(false),
    GetTheOtherObjectObject(false));

    factory->add_type_object("basic_struct", Getbasic_structIdentifier(true),
    Getbasic_structObject(true));
    factory->add_type_object("basic_struct", Getbasic_structIdentifier(false),
    Getbasic_structObject(false));

}

const TypeIdentifier* GetTheOtherObjectIdentifier(bool complete)
{
    const TypeIdentifier * c_identifier = TypeObjectFactory::get_instance()->get_type_identifier("TheOtherObject", complete);
    if (c_identifier != nullptr && (!complete || c_identifier->_d() == EK_COMPLETE))
    {
        return c_identifier;
    }

    GetTheOtherObjectObject(complete); // Generated inside
    return TypeObjectFactory::get_instance()->get_type_identifier("TheOtherObject", complete);
}

const TypeObject* GetTheOtherObjectObject(bool complete)
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("TheOtherObject", complete);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }
    else if (complete)
    {
        return GetCompleteTheOtherObjectObject();
    }
    //else
    return GetMinimalTheOtherObjectObject();
}

const TypeObject* GetMinimalTheOtherObjectObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("TheOtherObject", false);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_MINIMAL);
    type_object->minimal()._d(TK_STRUCTURE);

    type_object->minimal().struct_type().struct_flags().IS_FINAL(false);
    type_object->minimal().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_NESTED(false);
    type_object->minimal().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    MinimalStructMember mst_some_num;
    mst_some_num.common().member_id(memberId++);
    mst_some_num.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_some_num.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_some_num.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_some_num.common().member_flags().IS_OPTIONAL(false);
    mst_some_num.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_some_num.common().member_flags().IS_KEY(false);
    mst_some_num.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_some_num.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("int32_t", false));

    MD5 some_num_hash("some_num");
    for(int i = 0; i < 4; ++i)
    {
        mst_some_num.detail().name_hash()[i] = some_num_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_some_num);


    // Header
    // TODO Inheritance
    //type_object->minimal().struct_type().header().base_type()._d(EK_MINIMAL);
    //type_object->minimal().struct_type().header().base_type().equivalence_hash()[0..13];

    TypeIdentifier identifier;
    identifier._d(EK_MINIMAL);

    SerializedPayload_t payload(static_cast<uint32_t>(
        MinimalStructType::getCdrSerializedSize(type_object->minimal().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("TheOtherObject", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("TheOtherObject", false);
}

const TypeObject* GetCompleteTheOtherObjectObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("TheOtherObject", true);
    if (c_type_object != nullptr && c_type_object->_d() == EK_COMPLETE)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_COMPLETE);
    type_object->complete()._d(TK_STRUCTURE);

    type_object->complete().struct_type().struct_flags().IS_FINAL(false);
    type_object->complete().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->complete().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->complete().struct_type().struct_flags().IS_NESTED(false);
    type_object->complete().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    CompleteStructMember cst_some_num;
    cst_some_num.common().member_id(memberId++);
    cst_some_num.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_some_num.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_some_num.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_some_num.common().member_flags().IS_OPTIONAL(false);
    cst_some_num.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_some_num.common().member_flags().IS_KEY(false);
    cst_some_num.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_some_num.common().member_type_id(*TypeObjectFactory::get_instance()->get_type_identifier("int32_t", false));

    cst_some_num.detail().name("some_num");

    type_object->complete().struct_type().member_seq().emplace_back(cst_some_num);


    // Header
    type_object->complete().struct_type().header().detail().type_name("TheOtherObject");
    // TODO inheritance


    TypeIdentifier identifier;
    identifier._d(EK_COMPLETE);

    SerializedPayload_t payload(static_cast<uint32_t>(
        CompleteStructType::getCdrSerializedSize(type_object->complete().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("TheOtherObject", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("TheOtherObject", true);
}

const TypeIdentifier* Getbasic_structIdentifier(bool complete)
{
    const TypeIdentifier * c_identifier = TypeObjectFactory::get_instance()->get_type_identifier("basic_struct", complete);
    if (c_identifier != nullptr && (!complete || c_identifier->_d() == EK_COMPLETE))
    {
        return c_identifier;
    }

    Getbasic_structObject(complete); // Generated inside
    return TypeObjectFactory::get_instance()->get_type_identifier("basic_struct", complete);
}

const TypeObject* Getbasic_structObject(bool complete)
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("basic_struct", complete);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }
    else if (complete)
    {
        return GetCompletebasic_structObject();
    }
    //else
    return GetMinimalbasic_structObject();
}

const TypeObject* GetMinimalbasic_structObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("basic_struct", false);
    if (c_type_object != nullptr)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_MINIMAL);
    type_object->minimal()._d(TK_STRUCTURE);

    type_object->minimal().struct_type().struct_flags().IS_FINAL(false);
    type_object->minimal().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->minimal().struct_type().struct_flags().IS_NESTED(false);
    type_object->minimal().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    MinimalStructMember mst_sub_struct;
    mst_sub_struct.common().member_id(memberId++);
    mst_sub_struct.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    mst_sub_struct.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    mst_sub_struct.common().member_flags().IS_EXTERNAL(false); // Unsupported
    mst_sub_struct.common().member_flags().IS_OPTIONAL(false);
    mst_sub_struct.common().member_flags().IS_MUST_UNDERSTAND(false);
    mst_sub_struct.common().member_flags().IS_KEY(false);
    mst_sub_struct.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    mst_sub_struct.common().member_type_id(*GetTheOtherObjectIdentifier(false));
    MD5 sub_struct_hash("sub_struct");
    for(int i = 0; i < 4; ++i)
    {
        mst_sub_struct.detail().name_hash()[i] = sub_struct_hash.digest[i];
    }
    type_object->minimal().struct_type().member_seq().emplace_back(mst_sub_struct);


    // Header
    // TODO Inheritance
    //type_object->minimal().struct_type().header().base_type()._d(EK_MINIMAL);
    //type_object->minimal().struct_type().header().base_type().equivalence_hash()[0..13];

    TypeIdentifier identifier;
    identifier._d(EK_MINIMAL);

    SerializedPayload_t payload(static_cast<uint32_t>(
        MinimalStructType::getCdrSerializedSize(type_object->minimal().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("basic_struct", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("basic_struct", false);
}

const TypeObject* GetCompletebasic_structObject()
{
    const TypeObject* c_type_object = TypeObjectFactory::get_instance()->get_type_object("basic_struct", true);
    if (c_type_object != nullptr && c_type_object->_d() == EK_COMPLETE)
    {
        return c_type_object;
    }

    TypeObject *type_object = new TypeObject();
    type_object->_d(EK_COMPLETE);
    type_object->complete()._d(TK_STRUCTURE);

    type_object->complete().struct_type().struct_flags().IS_FINAL(false);
    type_object->complete().struct_type().struct_flags().IS_APPENDABLE(false);
    type_object->complete().struct_type().struct_flags().IS_MUTABLE(false);
    type_object->complete().struct_type().struct_flags().IS_NESTED(false);
    type_object->complete().struct_type().struct_flags().IS_AUTOID_HASH(false); // Unsupported

    MemberId memberId = 0;
    CompleteStructMember cst_sub_struct;
    cst_sub_struct.common().member_id(memberId++);
    cst_sub_struct.common().member_flags().TRY_CONSTRUCT1(false); // Unsupported
    cst_sub_struct.common().member_flags().TRY_CONSTRUCT2(false); // Unsupported
    cst_sub_struct.common().member_flags().IS_EXTERNAL(false); // Unsupported
    cst_sub_struct.common().member_flags().IS_OPTIONAL(false);
    cst_sub_struct.common().member_flags().IS_MUST_UNDERSTAND(false);
    cst_sub_struct.common().member_flags().IS_KEY(false);
    cst_sub_struct.common().member_flags().IS_DEFAULT(false); // Doesn't apply
    cst_sub_struct.common().member_type_id(*GetTheOtherObjectIdentifier(true));
    cst_sub_struct.detail().name("sub_struct");

    type_object->complete().struct_type().member_seq().emplace_back(cst_sub_struct);


    // Header
    type_object->complete().struct_type().header().detail().type_name("basic_struct");
    // TODO inheritance


    TypeIdentifier identifier;
    identifier._d(EK_COMPLETE);

    SerializedPayload_t payload(static_cast<uint32_t>(
        CompleteStructType::getCdrSerializedSize(type_object->complete().struct_type()) + 4));
    eprosima::fastcdr::FastBuffer fastbuffer((char*) payload.data, payload.max_size);
    // Fixed endian (Page 221, EquivalenceHash definition of Extensible and Dynamic Topic Types for DDS document)
    eprosima::fastcdr::Cdr ser(
        fastbuffer, eprosima::fastcdr::Cdr::LITTLE_ENDIANNESS,
        eprosima::fastcdr::Cdr::DDS_CDR); // Object that serializes the data.
    payload.encapsulation = CDR_LE;

    type_object->serialize(ser);
    payload.length = (uint32_t)ser.getSerializedDataLength(); //Get the serialized length
    MD5 objectHash;
    objectHash.update((char*)payload.data, payload.length);
    objectHash.finalize();
    for(int i = 0; i < 14; ++i)
    {
        identifier.equivalence_hash()[i] = objectHash.digest[i];
    }

    TypeObjectFactory::get_instance()->add_type_object("basic_struct", &identifier, type_object);
    delete type_object;
    return TypeObjectFactory::get_instance()->get_type_object("basic_struct", true);
}
