// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file complex_nested_arraysTypeObject.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_COMPLEX_NESTED_ARRAYS_TYPE_OBJECT_H_
#define _FAST_DDS_GENERATED_COMPLEX_NESTED_ARRAYS_TYPE_OBJECT_H_


#include <fastrtps/types/TypeObject.h>
#include <map>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(complex_nested_arrays_SOURCE)
#define complex_nested_arrays_DllAPI __declspec( dllexport )
#else
#define complex_nested_arrays_DllAPI __declspec( dllimport )
#endif // complex_nested_arrays_SOURCE
#else
#define complex_nested_arrays_DllAPI
#endif
#else
#define complex_nested_arrays_DllAPI
#endif // _WIN32

using namespace eprosima::fastrtps::types;

eProsima_user_DllExport void registercomplex_nested_arraysTypes();

eProsima_user_DllExport const TypeIdentifier* GetThirdLevelElementIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetThirdLevelElementObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalThirdLevelElementObject();
eProsima_user_DllExport const TypeObject* GetCompleteThirdLevelElementObject();

eProsima_user_DllExport const TypeIdentifier* GetSecondLevelElementIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetSecondLevelElementObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalSecondLevelElementObject();
eProsima_user_DllExport const TypeObject* GetCompleteSecondLevelElementObject();

eProsima_user_DllExport const TypeIdentifier* GetFirstLevelElementIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* GetFirstLevelElementObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalFirstLevelElementObject();
eProsima_user_DllExport const TypeObject* GetCompleteFirstLevelElementObject();

eProsima_user_DllExport const TypeIdentifier* Getcomplex_nested_arraysIdentifier(bool complete = false);
eProsima_user_DllExport const TypeObject* Getcomplex_nested_arraysObject(bool complete = false);
eProsima_user_DllExport const TypeObject* GetMinimalcomplex_nested_arraysObject();
eProsima_user_DllExport const TypeObject* GetCompletecomplex_nested_arraysObject();


#endif // _FAST_DDS_GENERATED_COMPLEX_NESTED_ARRAYS_TYPE_OBJECT_H_