# Nightly test workflow for DDS Record & Replay
name: nightly

on:
  schedule:
    - cron: '0 5 * * *'

jobs:

  reusable_tests_v2:
    name: reusable_tests_v2
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      custom_version_build: 'v2'
      dependencies_artifact_postfix: '_nightly'
      ref: '0.x'
    secrets: inherit

  reusable_tests_v3:
    name: reusable_tests_v3
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      custom_version_build: 'v3'
      dependencies_artifact_postfix: '_nightly'
      ref: 'main'
    secrets: inherit
