# Tests to run with workflow-dispatch, pull-request and push events
name: test

on:
  workflow_dispatch:
    inputs:

      custom_version_build:
        description: >
          Use the custom version build from eProsima-CI.
          If set to false, the workflow will run the tests for Fast DDS v2 and v3.
        required: true
        type: choice
        default: 'custom'
        options:
          - custom
          - v2
          - v3

      dependencies_artifact_postfix:
        description: 'Postfix name to add to artifact name to download dependencies. This is use to download a specific artifact version from eProsima-CI.'
        required: true
        default: '_nightly'

  pull_request:
  push:
    branches:
      - main

jobs:

  reusable_tests_ubuntu:
    name: ubuntu-ci
    uses: ./.github/workflows/reusable-ubuntu-ci.yml
    with:
      custom_version_build: ${{ inputs.custom_version_build || 'v3' }}
      dependencies_artifact_postfix: ${{ inputs.dependencies_artifact_postfix || '_nightly' }}
      ref: ${{ github.ref }}
    secrets: inherit

  reusable_tests_windows:
    name: windows-ci
    uses: ./.github/workflows/reusable-windows-ci.yml
    with:
      custom_version_build: ${{ inputs.custom_version_build || 'v3' }}
      dependencies_artifact_postfix: ${{ inputs.dependencies_artifact_postfix || '_nightly' }}
      ref: ${{ github.ref }}
    secrets: inherit
